version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: pass_123
      POSTGRES_USER: discordUser
      POSTGRES_DB: discordDB
    ports:
      - "5432:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql/data
volumes:
  my_dbdata:
